Repository ichika4561/Sports, pull requests merged in 2019-02, with the labels that each got.

#2 投稿時にエラー出てたので修正
  app/controllers/posts_controller.rb
  app/models/post.rb
  db/schema.rb
Labels: review me

#3 githubテンプレートの設定
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review me

#4 READMEにコンセプトの記入
  Gemfile
  Gemfile.lock
  README.md
Labels: LGTM

#13 correct routes about omniauth
  Gemfile
  app/controllers/users/omniauth_callbacks_controller.rb
  app/views/layouts/application.html.slim
Labels: invalid

#15 スキーマ設計の見直し
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/_form.html.slim
  app/views/posts/edit.html.slim
  app/views/posts/new.html.slim
  db/migrate/20190205095707_create_posts.rb
  db/schema.rb
  test/fixtures/posts.yml
  test/fixtures/users.yml
  test/models/post_test.rb
  test/models/user_test.rb
Labels: bug

#16 wip ログイン状態での投稿がうまくいかないエラーが発生。
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/models/area.rb
  app/models/genre.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/index.html.slim
  db/migrate/20190211050132_create_genres.rb
  db/migrate/20190211050259_create_areas.rb
  db/migrate/20190211110645_user_id_to_posts.rb
  db/schema.rb
  test/fixtures/areas.yml
  test/fixtures/genres.yml
  test/models/area_test.rb
  test/models/genre_test.rb
Labels: bug

#18 投稿機能のサンプルを実装
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/users/application_controller.rb
  app/controllers/users/posts_controller.rb
  app/decorators/post_decorator.rb
  app/models/application_record.rb
  app/models/area.rb
  app/models/genre.rb
  app/models/post.rb
  app/models/user.rb
  app/views/layouts/application.html.slim
  app/views/posts/_form.html.slim
  app/views/posts/edit.html.slim
  app/views/posts/index.html.slim
  app/views/posts/show.html.slim
  app/views/users/posts/_form.html.slim
  app/views/users/posts/edit.html.slim
  app/views/users/posts/index.html.slim
  app/views/users/posts/new.html.slim
  app/views/users/posts/show.html.slim
  config/initializers/simple_form.rb
  config/initializers/simple_form_bootstrap.rb
  config/locales/ja.yml
  config/locales/simple_form.en.yml
  config/routes.rb
  db/migrate/20190211110645_user_id_to_posts.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/area.rb
  db/seeds/genre.rb
  db/seeds/post.rb
  db/seeds/user.rb
  lib/templates/slim/scaffold/_form.html.slim
Labels: LGTM, review me

#20 WIP #9検索機能の実装
  app/assets/images/eyecatch.png
  app/assets/javascripts/top.coffee
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/top.scss
  app/controllers/application_controller.rb
  app/controllers/top_controller.rb
  app/controllers/users/posts_controller.rb
  app/helpers/top_helper.rb
  app/views/layouts/application.html.slim
  app/views/posts/index.html.slim
  app/views/top/index.html.slim
  app/views/users/posts/index.html.slim
  config/initializers/devise.rb
  config/locales/ja.yml
  config/routes.rb
  test/controllers/top_controller_test.rb
Labels: LGTM
